// ARCANA — données produits partagées (boutique, fiche produit, panier)
// ambiance: pastel | boho | night | sun  —  format: 78 | 44 | collector
window.PRODUCTS = [
    { id: 1,  name: "Tarot Solaire",      tag: "Tarot · Solaire",      cat: "tarot",     ambiance: "sun",   format: "78",        price: 59, old: null, rating: 5, reviews: 128, badge: "best", glyph: "☀", grad: "g-sun",   blurb: "78 lames dorées à chaud sur papier coton 350 g, livrées dans un coffret rigide. Lumineux, chaleureux, solaire." },
    { id: 2,  name: "Lune & Lame",        tag: "Tarot · Pastel",       cat: "tarot",     ambiance: "pastel",format: "78",        price: 49, old: null, rating: 4, reviews: 86,  badge: null,   glyph: "☾", grad: "g-rose",  blurb: "L'ésotérisme version pastel : des teintes douces et un trait délicat pour une lecture tout en tendresse." },
    { id: 3,  name: "Oracle Bohème",      tag: "Oracle · Bohème",      cat: "oracle",    ambiance: "boho",  format: "44",        price: 39, old: 45,   rating: 5, reviews: 64,  badge: "new",  glyph: "✶", grad: "g-boho",  blurb: "44 cartes à l'énergie nomade, inspirées des voyages et des grands espaces." },
    { id: 4,  name: "Arcanes Majeurs",    tag: "Tarot · Or sur nuit",  cat: "tarot",     ambiance: "night", format: "78",        price: 69, old: null, rating: 5, reviews: 203, badge: "best", glyph: "★", grad: "g-night", blurb: "L'édition or sur fond nuit. Élégante et mystérieuse, dorure sur tranche comprise." },
    { id: 5,  name: "Oracle des Astres",  tag: "Oracle · Or sur nuit", cat: "oracle",    ambiance: "night", format: "44",        price: 42, old: null, rating: 4, reviews: 41,  badge: null,   glyph: "✷", grad: "g-moon",  blurb: "Un oracle céleste de 44 cartes pour se reconnecter au ciel et à ses cycles." },
    { id: 6,  name: "Jeu Sur-Mesure",     tag: "Personnalisé",         cat: "custom",    ambiance: "pastel",format: "collector", price: 89, old: null, rating: 5, reviews: 312, badge: "new",  glyph: "✦", grad: "g-sun",   blurb: "Votre jeu, entièrement composé avec vous : style, symboles, palette et prénoms." },
    { id: 7,  name: "Coffret Pleine Lune",tag: "Tarot · Collector",    cat: "tarot",     ambiance: "night", format: "collector", price: 79, old: 89,   rating: 5, reviews: 57,  badge: null,   glyph: "◐", grad: "g-moon",  blurb: "Édition collector en série limitée, livret d'interprétation et coffret à fermoir." },
    { id: 8,  name: "Tapis de tirage",    tag: "Accessoire",           cat: "accessory", ambiance: null,    format: null,        price: 29, old: null, rating: 4, reviews: 38,  badge: null,   glyph: "⬟", grad: "g-rose",  blurb: "Tapis en velours 60×60 cm pour des tirages confortables et protégés." },
    { id: 9,  name: "Carte Cadeau",       tag: "À offrir",             cat: "gift",      ambiance: null,    format: null,        price: 50, old: null, rating: 5, reviews: 19,  badge: null,   glyph: "❤", grad: "g-boho",  blurb: "Offrez un tirage, offrez un signe. Montant de 25 à 150 €, valable 1 an." },
    { id: 10, name: "Oracle Pastel",      tag: "Oracle · Pastel",      cat: "oracle",    ambiance: "pastel",format: "44",        price: 37, old: null, rating: 4, reviews: 72,  badge: null,   glyph: "❀", grad: "g-rose",  blurb: "Un oracle doux et fleuri, parfait pour débuter en cartomancie." },
    { id: 11, name: "Tarot Nocturne",     tag: "Tarot · Or sur nuit",  cat: "tarot",     ambiance: "night", format: "78",        price: 64, old: null, rating: 5, reviews: 95,  badge: "best", glyph: "☽", grad: "g-night", blurb: "Profond et contrasté : un jeu pour les lectures introspectives du soir." },
    { id: 12, name: "Pochette velours",   tag: "Accessoire",           cat: "accessory", ambiance: null,    format: null,        price: 24, old: 29,   rating: 4, reviews: 26,  badge: null,   glyph: "◇", grad: "g-boho",  blurb: "Pochette en velours doublée pour ranger et transporter votre jeu en sécurité." },
];
